### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by quangtruong16994** [holyxiaoxin/react-native-slide-down-panel#2]
I want to build a slide down panel but your example not working with react native 0.40 and android platform. I haven't tested it on ios. 
How can I build a slide down panel like your gif?

**Comment by holyxiaoxin** [comment]
@quangtruong I'm no longer maintaining it. Someone made a pr to fix it. But I didn't publish the new fix. You can try installing this package referencing the source to git.

If you would like to see how it works you can look at the source code. It's pretty light. If you want to take over this project let me know (:

**Comment by ayyoobcastro** [comment]
not working your example

**Comment by jim-at-jibba** [comment]
@ayyoobcastro Hey, I have just replaced the example app. It works!

**Comment by holyxiaoxin** [comment]
Great job @jim-at-jibba!
