### ISSUE TITLE
I will become a maintianer if you are happy to add me.

### ISSUE THREAD

**Issue by jim-at-jibba** [holyxiaoxin/react-native-slide-down-panel#3]
Hey, 

This is a useful component but has not been touched in a while. I am happy to become a maintainer if you are keen to add me.

Let me know.

Cheers
James

**Comment by holyxiaoxin** [comment]
Awesome. I've shoot out the collab request. Thanks.

**Comment by jim-at-jibba** [comment]
Got it, thanks

**Comment by jim-at-jibba** [comment]
Once I have made some updates, what is the best way to republish to npm? Will you do it or would you rather add me to the packages registry?

**Comment by holyxiaoxin** [comment]
I'll add you to the registry. Username please?

**Comment by jim-at-jibba** [comment]
thanks

my username is jim-at-jibba

**Comment by holyxiaoxin** [comment]
done thanks. 👍
